Repository LawDigest/Lawbag, pull requests merged in 2024-12, with the labels that each got.

#381 Refactor(#Bill-Facade) mainFeed 코드 수정
  dbScripts/csvFiles/비례대표후보자정보.csv
  dbScripts/csvFiles/선거구코드.csv
  dbScripts/csvFiles/정당공약.csv
  dbScripts/csvFiles/정당코드.csv
  dbScripts/csvFiles/후보자정보.csv
  lawmaking/build.gradle
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/BillDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/BillInfoDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/PublicProposerDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/bill/BillDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/bill/Bills.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/proposer/RepresentativeProposerDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/BillDetailResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/BillListResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/PaginationResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/SearchBillResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/BillController.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/BillProposer.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/RepresentativeProposer.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/BillFacade.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/QuerydslConfig.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/constant/BillStageType.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/util/PaginationUtil.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepositoryCustom.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepositoryImpl.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/BillService.java
  lawmaking/src/main/resources/application.properties
  lawmaking/src/test/java/com/everyones/lawmaking/controller/BillControllerTest.java
  lawmaking/src/test/java/com/everyones/lawmaking/repository/BillReposiotryTest.java
Labels: enhancement, refactoring

#387 Feat(#Data-Automation-API) 법안 정보 삽입 시, party정보 추가
  lawmaking/src/main/java/com/everyones/lawmaking/service/DataService.java
Labels: bug

#389 법안 투표 시 정당 득표 순 정렬
  lawmaking/src/main/java/com/everyones/lawmaking/controller/BillController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/VotePartyRepository.java
Labels: fix

#390 팔로잉 탭 최근 의원이 발의한 순서로 반환 적용
  lawmaking/src/main/java/com/everyones/lawmaking/repository/CongressmanRepository.java
Labels: fix

#391 [FIX] 법안 API name필드와 imageUrl이 바뀌어서 나오는 문제 해결
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/proposer/RepresentativeProposerDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepositoryImpl.java
Labels: fix
