Repository LawDigest/Lawbag, pull requests merged in 2024-04, with the labels that each got.

#120 Feat : 정당별 비례대표 후보자 간단 정보 리스트 조회 API
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/ProportionalCandidateListDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/ProportionalCandidateListResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/PartyController.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/ProportionalCandidate.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/ProportionalCandidateRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/ProportionalCandidateService.java
Labels: feature

#127 Fix(#cors-https) Cors에 HTTPS 적용
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/CorsConfig.java
Labels: fix

#141 Feat(#Bill-Count-inParty) 정당 디테일 조회시 발의한 법안 개수 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/BillDetailInfo.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/BillInfoDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/PartyDetailResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/BillController.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Congressman.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Party.java
Labels: feature

#145 법안, 정당, 의원 좋아요 안정성 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/PartyDetailResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/UserController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/ResponseCode.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/BillService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/CongressmanService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/LikeService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/PartyService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/UserService.java
Labels: feature

#149 카카오 로그인 수정
  lawmaking/src/main/java/com/everyones/lawmaking/global/auth/PrincipalDetails.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/SecurityConfig.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/service/CustomOAuth2UserService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/AuthService.java
Labels: bug

#150 Fix : 로그아웃 시, 리다이렉션 uri 수정
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/SecurityConfig.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/handler/CustomLogoutSuccessHandler.java
Labels: bug

#154 쿠키 발급 수정 및 쿠키 삭제 수정
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/SecurityConfig.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/handler/CustomLogoutSuccessHandler.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/handler/OAuth2AuthenticationSuccessHandler.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/util/CookieUtil.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
Labels: bug, enhancement

#156 Feat : 선거구 조회 Api추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/CityNameResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/DistrictNameResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/DistrictResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/GuNameResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/DistrictController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/DistrictRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/DistrictService.java
Labels: feature

#160 Feat : 후보자 검색 Api 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/SearchCandidateDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/SearchController.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Candidate.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/CandidateRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/CandidateService.java
Labels: feature

#161 Feat : 비례대표 정당 정보 조회 api
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/ProportionalPartyResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/ProportionalCandidateController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/ProportionalCandidateRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/PartyService.java
Labels: feature

#163 Fix : 법안 검색 수정
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/SearchBillDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepository.java
Labels: bug

#166 Fix : 알림 메시지 조회 시, 쿼리 사용자별로 날리지 않게 수정
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/NotificationCreator.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/util/NotificationConverter.java
Labels: bug

#168 Feat : 비례대표 정당 페이지에서 정당 조회 api
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/ProportionalPartyResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/ProportionalCandidateController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/ProportionalCandidateRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/PartyService.java
Labels: bug, feature

#169 Feat : 선거구Id 조회 Api 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/DistrictIdResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/DistrictController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/DistrictRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/DistrictService.java
Labels: feature

#170 Fix : 후보자 검색 api에 후보자 이미지 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/SearchCandidateDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Candidate.java
Labels: bug

#171 시큐리티 권한 관리위한 토큰 검증 로직 수정 및 url 경로 수정 (with 토큰 jwt 만료에러 핸들링)
  lawmaking/src/main/java/com/everyones/lawmaking/controller/AuthController.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/BillController.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/CongressmanController.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/DistrictCandidateController.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/DistrictController.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/NotificationController.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/PartyController.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/ProportionalCandidateController.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Role.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/SecurityConfig.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/filterException/CustomAuthenticationEntryPoint.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/filterException/RestAuthenticationEntryPoint.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/handler/TokenAuthenticationFilter.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/jwt/AuthToken.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/jwt/AuthTokenProvider.java
Labels: bug
