Repository LawDigest/Lawbag, pull requests merged in 2024-08, with the labels that each got.

#256 Feat(#Following-Tab) 팔로잉 탭 임시 API 완성
  lawmaking/src/main/java/com/everyones/lawmaking/controller/FollowingTabController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/BillService.java
Labels: feature

#266 Fix(#Congressman) 의원 정보 api 수정
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/CongressmanResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Congressman.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/util/DateUtil.java
Labels: feature

#270 FIx(#Bill-Index) 법안 복합 인덱스 수정
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Bill.java
Labels: bug

#271 Fix(#Congressman-Bill-Count) 의원의 법안 카운트 로직 변경
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/CongressmanResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/CongressmanController.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Congressman.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillProposerRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/CongressmanLikeRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/RepresentativeProposerRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/BillProposerService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/CongressmanService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/DataService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/LikeService.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/RepresentativeProposerService.java
Labels: fix

#272 Fix(#Congressman-telephone) Congressman 누락 필드 'telephone' 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/CongressmanResponse.java
Labels: fix

#283 Fix(#Similar-BIll) 다른 개정안 보기 수정
  lawmaking/build.gradle
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/PartyDto.java
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/SimilarBill.java
Labels: enhancement

#284 Fix(#Following-Tab) 팔로잉탭 정당 이미지 필드 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/LikingCongressmanResponse.java
  lawmaking/src/main/resources/application.properties
Labels: enhancement

#291 Fix(#Congressman-Bill-Order) 의원이 발의한 법안 최신순 적용
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepository.java
Labels: fix

#296 Feat(#Congressman-brief-history) 의원 약력 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/CongressmanResponse.java
Labels: enhancement

#305 의원 정당 검색에서 무한스크롤 기능을 위한 pagination 삭제
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/SearchDataResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/SearchController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/CongressmanRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/CongressmanService.java
Labels: enhancement

#308 비례대표, 지역구 의원 카운트 업데이트 api
  lawmaking/src/main/java/com/everyones/lawmaking/controller/DataController.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Party.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/QuerydslConfig.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/CongressmanRepositoryCustom.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/DataService.java
Labels: enhancement
