Repository LawDigest/Lawbag, pull requests merged in 2025-01, with the labels that each got.

#395 [BE] 메인 피드를 제외한 대표 발의자의 party_image_url과 party_name이 바뀌어서 나오는 문제 해결
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/proposer/RepresentativeProposerDto.java
Labels: fix

#397 Feat(#billtimeline-bill-state)현재 국회의 법안 처리 상태 반환 API 완료
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/BillStateCountResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/controller/BillTimelineController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/BillFacade.java
  lawmaking/src/main/java/com/everyones/lawmaking/global/constant/BillInfoConstant.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/BillService.java
Labels: feature

#401 Fix(#Notification-Valid) 알림 증축 시, 유효성 검증
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/NotificationCreator.java
Labels: bug

#402 Feat(#BillTimeline-Introduction) 법안 타임라인 접수된 법안 추가
  lawmaking/src/main/java/com/everyones/lawmaking/common/dto/response/BillTimelineResponse.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/BillTimelineService.java
Labels: feature

#403 Fix(#Bill-Create-Modified) 법안 생성 및 수정 컬럼 추가
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Bill.java
Labels: enhancement

#404 Fix(#Bill-Search) 법안 검색 search 제안날짜 정렬
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillRepository.java
Labels: enhancement
