Repository LawDigest/Lawbag, pull requests merged in 2025-02, with the labels that each got.

#405 Fix(#Congressman-#Representative- dateColumns) 데이터 생성, 수정 날짜 필드 누락
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/Congressman.java
  lawmaking/src/main/java/com/everyones/lawmaking/domain/entity/RepresentativeProposer.java
Labels: enhancement

#408 Fix(#Notification) 데이터 쓰기 이벤트 시 반응 안함.
  lawmaking/src/main/java/com/everyones/lawmaking/global/config/TableEventListener.java
Labels: bug

#410 Feat(#BillTimeline-paging) 타임라인 페이징 기능 추가
  lawmaking/src/main/java/com/everyones/lawmaking/controller/BillTimelineController.java
  lawmaking/src/main/java/com/everyones/lawmaking/facade/Facade.java
  lawmaking/src/main/java/com/everyones/lawmaking/repository/BillTimelineRepository.java
  lawmaking/src/main/java/com/everyones/lawmaking/service/BillTimelineService.java
Labels: feature
